name: Build C++ EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Find C++ source
        shell: cmd
        run: |
          echo ===== C++ FILES =====
          dir /s /b *.cpp
          echo ====================

      - name: Build EXE
        shell: cmd
        run: |
          setlocal EnableDelayedExpansion
          set "SOURCE="

          for /r %%F in (*.cpp) do (
            if not defined SOURCE set "SOURCE=%%F"
          )

          if not defined SOURCE (
            echo.
            echo ERROR: Tidak ada file .cpp di repository!
            exit /b 1
          )

          echo Source ditemukan:
          echo !SOURCE!
          echo.

          g++ "!SOURCE!" ^
            -o program.exe ^
            -static ^
            -static-libgcc ^
            -static-libstdc++ ^
            -static-libwinpthread

          if errorlevel 1 (
            echo.
            echo ERROR: Compile gagal.
            exit /b 1
          )

          echo.
          echo BUILD BERHASIL!
          dir program.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: program.exe
